export const ADD_ALL_INVOICES = "ADD_ALL_INVOICES";
export const REMOVE_ALL_INVOICES = "REMOVE_ALL_INVOICES";
export const REMOVE_INVOICE_BY_INDEX = "REMOVE_INVOICE_BY_INDEX";
export const ADD_CURRENT_INVOICE = "ADD_CURRENT_INVOICE";
export const ADD_CURRENT_INVOICE_ITEMS = "ADD_CURRENT_INVOICE_ITEMS";
export const DELETE_CURRENT_INVOICE_ITEM_BY_INDEX =
    "DELETE_CURRENT_INVOICE_ITEM_BY_INDEX";
export const REMOVE_CURRENT_INVOICE = "REMOVE_CURRENT_INVOICE";
export const REMOVE_CURRENT_INVOICE_ITEMS = "REMOVE_CURRENT_INVOICE_ITEMS";
