export const ADD_ALL_INVOICES = "ADD_ALL_INVOICES";
export const ADD_CURRENT_INVOICE = "ADD_CURRENT_INVOICE";
export const ADD_CURRENT_CART_ITEMS = "ADD_CURRENT_CART_ITEMS";
export const DELETE_CURRENT_CART_ITEM_BY_INDEX =
    "DELETE_CURRENT_CART_ITEM_BY_INDEX";
export const REMOVE_CURRENT_INVOICE = "REMOVE_CURRENT_INVOICE";
export const REMOVE_CURRENT_CART_ITEMS = "REMOVE_CURRENT_CART_ITEMS";
